### ISSUE TITLE
Default example doesn't work without working tokenURI

### ISSUE THREAD

**Issue by iainnash** [ProjectOpenSea/operator-filter-registry#19]
After trying to get royalty fees working on görli, I realized that a valid tokenURI is required to get the controls for creator fees working.

The examples here return a blank tokenURI and it could be replaced with an example token such as `https://www.721.so/api/example/metadata/1`.

**Comment by Slokh** [comment]
tokenURI should not be required, can you try deploying without it again?

**Comment by iainnash** [comment]
https://goerli.etherscan.io/address/0xf1fce304a4353c2f7f359686e9105369af4b8c26#code

<img width="690" alt="Screen Shot 2022-11-10 at 10 06 01 PM" src="https://user-images.githubusercontent.com/835896/201254424-c3802bcc-8180-485f-9dfc-4b4b33e55f86.png">


Shows an example of a token with no token uri and 3 mints that doesn't show the editing field.

Same code with tokenURI:
https://goerli.etherscan.io/address/0x7a774798f652b959d9cad041c27d90910b4cbf82#readContract

<img width="750" alt="Screen Shot 2022-11-10 at 10 08 07 PM" src="https://user-images.githubusercontent.com/835896/201254412-4feb5162-b06a-4daa-896e-2326969b3b4e.png">

**Comment by itsanishjain** [comment]
It seems weird my contract is almost same Yes I updated the token URI thing I also taught that was issue.
Here is my opensea link

**Comment by itsanishjain** [comment]
Yes @iainnash your code is working let me try with ERC721A and let see

**Comment by ashrhmn** [comment]
Hey @iainnash , I can see the creators fee is enabled on OpenSea for my collection. But my contract URI response contains a seller fee basis points and the address which should be automatically set to royalty destination and percentages(It was working before 8th November). But my royalty percentage is always set to 0% right now even after implementing the `DefaultOperatorFilterer` and adding modifier to all transfer functions. Both `tokenURI` and `contractURI` has valid data (Not IPFS, but an HTTP address)

<img width="605" alt="image" src="https://user-images.githubusercontent.com/43120823/201491095-c2c5bce0-d170-4539-b6e0-0b8a59e58c3a.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/43120823/201491217-9d850635-0958-4ea0-988d-05503315e6ff.png">

Is this the expected behavior right now or am I missing something? Can you confirm?

**Comment by operatorfilterer** [comment]
We are investigating this issue as related to OpenSea ingestion of new smart contracts – setting a tokenURI should not be required for creator fee enforcement.

**Comment by operatorfilterer** [comment]
Closing, as Goerli validation has been updated - please create a new issue if you run into similar problems.
